[owner]
name = "Yulian Zavodnyk"
email="yulianzavodnyk@gmail.com"

[project]
name = "Sorting_App"
version = "0.0.1"
description = "Application for array sorting using fast sorting algorithms"
readme = "README.md"
license = {file = "LICENSE"}
